apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psmdb-db
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: psmdb-db
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.20.0
    helm:
      releaseName: psmdb-db
      valuesObject:
        crVersion: "1.20.0"  # Defines the CR version explicitly
        replsets:
          rs0:
            size: 3  # Defines the number of replica set members
            expose:
              enabled: true  # Allows external access to the replica set
            resources:
              requests:
                cpu: "600m"
                memory: "1G"
              limits:
                cpu: "600m"
                memory: "1G"
            volumeSpec:
              persistentVolumeClaim:
                resources:
                  requests:
                    storage: 20Gi  # Defines storage allocation
        backup:
          enabled: false  # Disables automated backups
        sharding:
          enabled: false  # Disables sharding
        enableVolumeExpansion: true  # Allows expanding PVC size without recreating it
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Ensures proper resource application
