apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: psmdb-operator
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.20.0
    helm:
      releaseName: mongodb-operator
      valuesObject:
        image:
          repository: percona/percona-server-mongodb-operator
          tag: 1.20.0
        watchNamespace: clusters 
        rbac:
          create: true 
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: "0"
