apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: psmdb-operator
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.20.0
    helm:
      releaseName: mongodb-operator
      valuesObject:
        image:
          repository: percona/percona-server-mongodb-operator
          tag: 1.20.0
        watchNamespace: clusters  # 👀 Specifies which namespace the operator should monitor
        rbac:
          create: true  # ✅ Ensures RBAC is properly created
        serviceAccount:
          create: true  # 🔹 Creates a ServiceAccount for the operator
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # 🚀 Helps avoid issues with large metadata annotations
  syncWave: "0"  # 🔄 Ensures the operator is deployed first
